// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(dashboard)/brand/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/brand">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/brand/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/files/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/files">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/files/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/bible-studies/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/bible-studies/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/bible-studies/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/bible-studies/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/bible-studies/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/bible-studies/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/bible-studies/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/bible-studies">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/bible-studies/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/content/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/content">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/content/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/events/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/events/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/events/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/events/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/events/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/events/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/events/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/events">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/events/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/photos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/photos">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/photos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/serving/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/serving/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/serving/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/serving/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/serving/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/serving/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/website/serving/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/website/serving">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/website/serving/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
