var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/brand/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__19lw6kt._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1bzk5nq._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01h2p23._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_1oy1nwh.js")
R.c("server/chunks/ssr/[root-of-the-server]__1kmt7hm._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/src_0okyayg._.js")
R.c("server/chunks/ssr/_1y4ig_s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_18_d8l1._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(dashboard)_brand_page_actions_0_ch7l8.js")
R.m(64507)
module.exports=R.m(64507).exports
